name: Paycare Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.25"
        
      - name: Build docker image
        run: docker build --build-arg PYTHON_VERSION=3.9.25 -t paycare .

      - name: Build docker image
        run: docker run -d -p 8070:8070 --name paycare-service paycare

      - name: Show container logs
        run: docker logs paycare-service

      - name: Run tests using pytest
        run: pytest -v

      - name: Stop and remove container
        run: docker stop paycare-service && docker rm paycare-service

